### ISSUE TITLE
Add Settings option for customizing low/high duration tolerances at runtime

### ISSUE THREAD

**Issue by david-vankampen** [saleae/async-rgb-led-analyzer#6]
Suggestion: Add a boolean settings option that allows the user to input their own low/high tolerances.  This would make it so that for every new serial RGB LED that comes out, this analyzer doesn't need to be updated with another drop-down option - the user can just tune it to their own.  

I could see it working 2 ways - either it pre-populates the values based on what you selected, or it only becomes active if you select a new "custom" LED from the dropdown menu.  I am not sure if settings can "interact" like that though (i.e. enable/disable/update setting A based on the value in setting B).

**Comment by schmicro** [comment]
Thanks for the suggestion! If there's a specific LED you'd like us to support, please let us know and reopen this issue. Unfortunately right now our analyzer settings are extremely static and inflexible, so adding optional settings is not currently supported.
